-- Skipping OrderDetails because it does not have a primary key
-- Skipping Permissions because it does not have a primary key
-- Skipping ProductStatus because it does not have a primary key
-- Skipping UserRoles because it does not have a primary key
--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertAction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertAction]

IF OBJECT_ID(N'[dbo].[usp_UpdateAction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateAction]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateAction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateAction]

IF OBJECT_ID(N'[dbo].[usp_DeleteAction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteAction]

IF OBJECT_ID(N'[dbo].[usp_DeleteActionsDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteActionsDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectAction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectAction]

IF OBJECT_ID(N'[dbo].[usp_SelectActionsDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectActionsDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectActionsPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectActionsPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectActionsAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectActionsAll]

--endregion

GO

--region [dbo].[usp_InsertAction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertAction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertAction]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Actions] (
	[id],
	[name]
) VALUES (
	@id,
	@name
)

--endregion

GO

--region [dbo].[usp_UpdateAction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateAction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateAction]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

UPDATE [dbo].[Actions] SET
	[name] = @name
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateAction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateAction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateAction]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Actions] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Actions] SET
		[name] = @name
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Actions] (
		[id],
		[name]
	) VALUES (
		@id,
		@name
	)
END

--endregion

GO

--region [dbo].[usp_DeleteAction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteAction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteAction]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Actions]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteActionsDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteActionsDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteActionsDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Actions]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectAction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectAction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectAction]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Actions]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectActionsDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectActionsDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectActionsDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[name]
FROM
	[dbo].[Actions]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectActionsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectActionsAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectActionsAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Actions]

--endregion

GO

--region [dbo].[usp_SelectActionsPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectActionsPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectActionsPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Actions]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertCategory]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertCategory]

IF OBJECT_ID(N'[dbo].[usp_UpdateCategory]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateCategory]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateCategory]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateCategory]

IF OBJECT_ID(N'[dbo].[usp_DeleteCategory]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteCategory]

IF OBJECT_ID(N'[dbo].[usp_DeleteCategoriesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteCategoriesDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectCategory]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectCategory]

IF OBJECT_ID(N'[dbo].[usp_SelectCategoriesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectCategoriesDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectCategoriesPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectCategoriesPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectCategoriesAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectCategoriesAll]

--endregion

GO

--region [dbo].[usp_InsertCategory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertCategory]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertCategory]
	@id nchar(10),
	@name nvarchar(50),
	@isShowOnHome bit,
	@status bit
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Categories] (
	[id],
	[name],
	[isShowOnHome],
	[status]
) VALUES (
	@id,
	@name,
	@isShowOnHome,
	@status
)

--endregion

GO

--region [dbo].[usp_UpdateCategory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateCategory]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateCategory]
	@id nchar(10),
	@name nvarchar(50),
	@isShowOnHome bit,
	@status bit
AS

SET NOCOUNT ON

UPDATE [dbo].[Categories] SET
	[name] = @name,
	[isShowOnHome] = @isShowOnHome,
	[status] = @status
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateCategory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateCategory]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateCategory]
	@id nchar(10),
	@name nvarchar(50),
	@isShowOnHome bit,
	@status bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Categories] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Categories] SET
		[name] = @name,
		[isShowOnHome] = @isShowOnHome,
		[status] = @status
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Categories] (
		[id],
		[name],
		[isShowOnHome],
		[status]
	) VALUES (
		@id,
		@name,
		@isShowOnHome,
		@status
	)
END

--endregion

GO

--region [dbo].[usp_DeleteCategory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteCategory]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteCategory]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Categories]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteCategoriesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteCategoriesDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteCategoriesDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Categories]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectCategory]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectCategory]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectCategory]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[isShowOnHome],
	[status]
FROM
	[dbo].[Categories]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectCategoriesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectCategoriesDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectCategoriesDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[name],
	[isShowOnHome],
	[status]
FROM
	[dbo].[Categories]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectCategoriesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectCategoriesAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectCategoriesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[isShowOnHome],
	[status]
FROM
	[dbo].[Categories]

--endregion

GO

--region [dbo].[usp_SelectCategoriesPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectCategoriesPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectCategoriesPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[isShowOnHome],
	[status]
FROM
	[dbo].[Categories]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertFunction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertFunction]

IF OBJECT_ID(N'[dbo].[usp_UpdateFunction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateFunction]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateFunction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateFunction]

IF OBJECT_ID(N'[dbo].[usp_DeleteFunction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteFunction]

IF OBJECT_ID(N'[dbo].[usp_DeleteFunctionsDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteFunctionsDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectFunction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectFunction]

IF OBJECT_ID(N'[dbo].[usp_SelectFunctionsDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectFunctionsDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectFunctionsPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectFunctionsPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectFunctionsAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectFunctionsAll]

--endregion

GO

--region [dbo].[usp_InsertFunction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertFunction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertFunction]
	@id nchar(10),
	@name nvarchar(50),
	@url nchar(255),
	@parentId nchar(10),
	@status bit
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Functions] (
	[id],
	[name],
	[url],
	[parentId],
	[status]
) VALUES (
	@id,
	@name,
	@url,
	@parentId,
	@status
)

--endregion

GO

--region [dbo].[usp_UpdateFunction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateFunction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateFunction]
	@id nchar(10),
	@name nvarchar(50),
	@url nchar(255),
	@parentId nchar(10),
	@status bit
AS

SET NOCOUNT ON

UPDATE [dbo].[Functions] SET
	[name] = @name,
	[url] = @url,
	[parentId] = @parentId,
	[status] = @status
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateFunction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateFunction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateFunction]
	@id nchar(10),
	@name nvarchar(50),
	@url nchar(255),
	@parentId nchar(10),
	@status bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Functions] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Functions] SET
		[name] = @name,
		[url] = @url,
		[parentId] = @parentId,
		[status] = @status
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Functions] (
		[id],
		[name],
		[url],
		[parentId],
		[status]
	) VALUES (
		@id,
		@name,
		@url,
		@parentId,
		@status
	)
END

--endregion

GO

--region [dbo].[usp_DeleteFunction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteFunction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteFunction]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Functions]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteFunctionsDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteFunctionsDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteFunctionsDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Functions]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectFunction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectFunction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectFunction]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[url],
	[parentId],
	[status]
FROM
	[dbo].[Functions]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectFunctionsDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectFunctionsDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectFunctionsDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[name],
	[url],
	[parentId],
	[status]
FROM
	[dbo].[Functions]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectFunctionsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectFunctionsAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectFunctionsAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[url],
	[parentId],
	[status]
FROM
	[dbo].[Functions]

--endregion

GO

--region [dbo].[usp_SelectFunctionsPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectFunctionsPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectFunctionsPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[url],
	[parentId],
	[status]
FROM
	[dbo].[Functions]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertOrder]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertOrder]

IF OBJECT_ID(N'[dbo].[usp_UpdateOrder]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateOrder]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateOrder]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateOrder]

IF OBJECT_ID(N'[dbo].[usp_DeleteOrder]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteOrder]

IF OBJECT_ID(N'[dbo].[usp_DeleteOrdersDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteOrdersDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectOrder]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectOrder]

IF OBJECT_ID(N'[dbo].[usp_SelectOrdersDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectOrdersDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectOrdersPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectOrdersPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectOrdersAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectOrdersAll]

IF OBJECT_ID(N'[dbo].[usp_SelectOrdersBytypeId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectOrdersBytypeId]

IF OBJECT_ID(N'[dbo].[usp_SelectOrdersByuserId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectOrdersByuserId]

IF OBJECT_ID(N'[dbo].[usp_DeleteOrdersBytypeId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteOrdersBytypeId]

IF OBJECT_ID(N'[dbo].[usp_DeleteOrdersByuserId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteOrdersByuserId]

--endregion

GO

--region [dbo].[usp_InsertOrder]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertOrder]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertOrder]
	@id nchar(10),
	@createdBy nchar(10),
	@userId nchar(10),
	@orderDate datetime,
	@shipName nvarchar(50),
	@shipAddress nvarchar(255),
	@shipPhoneNumber nchar(20),
	@status int,
	@typeId nchar(10),
	@fee float,
	@discount float,
	@total float
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Orders] (
	[id],
	[createdBy],
	[userId],
	[orderDate],
	[shipName],
	[shipAddress],
	[shipPhoneNumber],
	[status],
	[typeId],
	[fee],
	[discount],
	[total]
) VALUES (
	@id,
	@createdBy,
	@userId,
	@orderDate,
	@shipName,
	@shipAddress,
	@shipPhoneNumber,
	@status,
	@typeId,
	@fee,
	@discount,
	@total
)

--endregion

GO

--region [dbo].[usp_UpdateOrder]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateOrder]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateOrder]
	@id nchar(10),
	@createdBy nchar(10),
	@userId nchar(10),
	@orderDate datetime,
	@shipName nvarchar(50),
	@shipAddress nvarchar(255),
	@shipPhoneNumber nchar(20),
	@status int,
	@typeId nchar(10),
	@fee float,
	@discount float,
	@total float
AS

SET NOCOUNT ON

UPDATE [dbo].[Orders] SET
	[createdBy] = @createdBy,
	[userId] = @userId,
	[orderDate] = @orderDate,
	[shipName] = @shipName,
	[shipAddress] = @shipAddress,
	[shipPhoneNumber] = @shipPhoneNumber,
	[status] = @status,
	[typeId] = @typeId,
	[fee] = @fee,
	[discount] = @discount,
	[total] = @total
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateOrder]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateOrder]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateOrder]
	@id nchar(10),
	@createdBy nchar(10),
	@userId nchar(10),
	@orderDate datetime,
	@shipName nvarchar(50),
	@shipAddress nvarchar(255),
	@shipPhoneNumber nchar(20),
	@status int,
	@typeId nchar(10),
	@fee float,
	@discount float,
	@total float
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Orders] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Orders] SET
		[createdBy] = @createdBy,
		[userId] = @userId,
		[orderDate] = @orderDate,
		[shipName] = @shipName,
		[shipAddress] = @shipAddress,
		[shipPhoneNumber] = @shipPhoneNumber,
		[status] = @status,
		[typeId] = @typeId,
		[fee] = @fee,
		[discount] = @discount,
		[total] = @total
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Orders] (
		[id],
		[createdBy],
		[userId],
		[orderDate],
		[shipName],
		[shipAddress],
		[shipPhoneNumber],
		[status],
		[typeId],
		[fee],
		[discount],
		[total]
	) VALUES (
		@id,
		@createdBy,
		@userId,
		@orderDate,
		@shipName,
		@shipAddress,
		@shipPhoneNumber,
		@status,
		@typeId,
		@fee,
		@discount,
		@total
	)
END

--endregion

GO

--region [dbo].[usp_DeleteOrder]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteOrder]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteOrder]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Orders]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteOrdersBytypeId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteOrdersBytypeId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteOrdersBytypeId]
	@typeId nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Orders]
WHERE
	[typeId] = @typeId

GO

--endregion

GO

--region [dbo].[usp_DeleteOrdersByuserId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteOrdersByuserId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteOrdersByuserId]
	@userId nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Orders]
WHERE
	[userId] = @userId

GO

--endregion

GO

--region [dbo].[usp_DeleteOrdersDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteOrdersDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteOrdersDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Orders]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectOrder]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectOrder]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectOrder]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[createdBy],
	[userId],
	[orderDate],
	[shipName],
	[shipAddress],
	[shipPhoneNumber],
	[status],
	[typeId],
	[fee],
	[discount],
	[total]
FROM
	[dbo].[Orders]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectOrdersBytypeId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectOrdersBytypeId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectOrdersBytypeId]
	@typeId nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[createdBy],
	[userId],
	[orderDate],
	[shipName],
	[shipAddress],
	[shipPhoneNumber],
	[status],
	[typeId],
	[fee],
	[discount],
	[total]
FROM
	[dbo].[Orders]
WHERE
	[typeId] = @typeId

--endregion

GO

--region [dbo].[usp_SelectOrdersByuserId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectOrdersByuserId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectOrdersByuserId]
	@userId nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[createdBy],
	[userId],
	[orderDate],
	[shipName],
	[shipAddress],
	[shipPhoneNumber],
	[status],
	[typeId],
	[fee],
	[discount],
	[total]
FROM
	[dbo].[Orders]
WHERE
	[userId] = @userId

--endregion

GO

--region [dbo].[usp_SelectOrdersDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectOrdersDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectOrdersDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[createdBy],
	[userId],
	[orderDate],
	[shipName],
	[shipAddress],
	[shipPhoneNumber],
	[status],
	[typeId],
	[fee],
	[discount],
	[total]
FROM
	[dbo].[Orders]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectOrdersAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectOrdersAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectOrdersAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[createdBy],
	[userId],
	[orderDate],
	[shipName],
	[shipAddress],
	[shipPhoneNumber],
	[status],
	[typeId],
	[fee],
	[discount],
	[total]
FROM
	[dbo].[Orders]

--endregion

GO

--region [dbo].[usp_SelectOrdersPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectOrdersPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectOrdersPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[createdBy],
	[userId],
	[orderDate],
	[shipName],
	[shipAddress],
	[shipPhoneNumber],
	[status],
	[typeId],
	[fee],
	[discount],
	[total]
FROM
	[dbo].[Orders]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertProduct]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertProduct]

IF OBJECT_ID(N'[dbo].[usp_UpdateProduct]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateProduct]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateProduct]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateProduct]

IF OBJECT_ID(N'[dbo].[usp_DeleteProduct]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteProduct]

IF OBJECT_ID(N'[dbo].[usp_DeleteProductsDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteProductsDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectProduct]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectProduct]

IF OBJECT_ID(N'[dbo].[usp_SelectProductsDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectProductsDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectProductsPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectProductsPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectProductsAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectProductsAll]

IF OBJECT_ID(N'[dbo].[usp_SelectProductsBycategoriesId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectProductsBycategoriesId]

IF OBJECT_ID(N'[dbo].[usp_DeleteProductsBycategoriesId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteProductsBycategoriesId]

--endregion

GO

--region [dbo].[usp_InsertProduct]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertProduct]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertProduct]
	@id nchar(10),
	@name nvarchar(50),
	@description nvarchar(255),
	@price float,
	@details nvarchar(255),
	@isShowOnHome bit,
	@discount float,
	@quantityOrder int,
	@image nchar(255),
	@categoriesId nchar(10)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Products] (
	[id],
	[name],
	[description],
	[price],
	[details],
	[isShowOnHome],
	[discount],
	[quantityOrder],
	[image],
	[categoriesId]
) VALUES (
	@id,
	@name,
	@description,
	@price,
	@details,
	@isShowOnHome,
	@discount,
	@quantityOrder,
	@image,
	@categoriesId
)

--endregion

GO

--region [dbo].[usp_UpdateProduct]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateProduct]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateProduct]
	@id nchar(10),
	@name nvarchar(50),
	@description nvarchar(255),
	@price float,
	@details nvarchar(255),
	@isShowOnHome bit,
	@discount float,
	@quantityOrder int,
	@image nchar(255),
	@categoriesId nchar(10)
AS

SET NOCOUNT ON

UPDATE [dbo].[Products] SET
	[name] = @name,
	[description] = @description,
	[price] = @price,
	[details] = @details,
	[isShowOnHome] = @isShowOnHome,
	[discount] = @discount,
	[quantityOrder] = @quantityOrder,
	[image] = @image,
	[categoriesId] = @categoriesId
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateProduct]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateProduct]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateProduct]
	@id nchar(10),
	@name nvarchar(50),
	@description nvarchar(255),
	@price float,
	@details nvarchar(255),
	@isShowOnHome bit,
	@discount float,
	@quantityOrder int,
	@image nchar(255),
	@categoriesId nchar(10)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Products] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Products] SET
		[name] = @name,
		[description] = @description,
		[price] = @price,
		[details] = @details,
		[isShowOnHome] = @isShowOnHome,
		[discount] = @discount,
		[quantityOrder] = @quantityOrder,
		[image] = @image,
		[categoriesId] = @categoriesId
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Products] (
		[id],
		[name],
		[description],
		[price],
		[details],
		[isShowOnHome],
		[discount],
		[quantityOrder],
		[image],
		[categoriesId]
	) VALUES (
		@id,
		@name,
		@description,
		@price,
		@details,
		@isShowOnHome,
		@discount,
		@quantityOrder,
		@image,
		@categoriesId
	)
END

--endregion

GO

--region [dbo].[usp_DeleteProduct]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteProduct]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteProduct]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Products]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteProductsBycategoriesId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteProductsBycategoriesId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteProductsBycategoriesId]
	@categoriesId nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Products]
WHERE
	[categoriesId] = @categoriesId

GO

--endregion

GO

--region [dbo].[usp_DeleteProductsDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteProductsDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteProductsDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Products]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectProduct]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectProduct]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectProduct]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[description],
	[price],
	[details],
	[isShowOnHome],
	[discount],
	[quantityOrder],
	[image],
	[categoriesId]
FROM
	[dbo].[Products]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectProductsBycategoriesId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectProductsBycategoriesId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectProductsBycategoriesId]
	@categoriesId nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[description],
	[price],
	[details],
	[isShowOnHome],
	[discount],
	[quantityOrder],
	[image],
	[categoriesId]
FROM
	[dbo].[Products]
WHERE
	[categoriesId] = @categoriesId

--endregion

GO

--region [dbo].[usp_SelectProductsDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectProductsDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectProductsDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[name],
	[description],
	[price],
	[details],
	[isShowOnHome],
	[discount],
	[quantityOrder],
	[image],
	[categoriesId]
FROM
	[dbo].[Products]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectProductsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectProductsAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectProductsAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[description],
	[price],
	[details],
	[isShowOnHome],
	[discount],
	[quantityOrder],
	[image],
	[categoriesId]
FROM
	[dbo].[Products]

--endregion

GO

--region [dbo].[usp_SelectProductsPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectProductsPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectProductsPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name],
	[description],
	[price],
	[details],
	[isShowOnHome],
	[discount],
	[quantityOrder],
	[image],
	[categoriesId]
FROM
	[dbo].[Products]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertRole]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertRole]

IF OBJECT_ID(N'[dbo].[usp_UpdateRole]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateRole]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateRole]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateRole]

IF OBJECT_ID(N'[dbo].[usp_DeleteRole]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteRole]

IF OBJECT_ID(N'[dbo].[usp_DeleteRolesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteRolesDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectRole]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectRole]

IF OBJECT_ID(N'[dbo].[usp_SelectRolesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectRolesDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectRolesPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectRolesPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectRolesAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectRolesAll]

--endregion

GO

--region [dbo].[usp_InsertRole]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertRole]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertRole]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Roles] (
	[id],
	[name]
) VALUES (
	@id,
	@name
)

--endregion

GO

--region [dbo].[usp_UpdateRole]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateRole]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateRole]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

UPDATE [dbo].[Roles] SET
	[name] = @name
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateRole]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateRole]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateRole]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Roles] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Roles] SET
		[name] = @name
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Roles] (
		[id],
		[name]
	) VALUES (
		@id,
		@name
	)
END

--endregion

GO

--region [dbo].[usp_DeleteRole]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteRole]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteRole]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Roles]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteRolesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteRolesDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteRolesDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Roles]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectRole]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectRole]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectRole]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Roles]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectRolesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectRolesDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectRolesDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[name]
FROM
	[dbo].[Roles]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectRolesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectRolesAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectRolesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Roles]

--endregion

GO

--region [dbo].[usp_SelectRolesPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectRolesPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectRolesPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Roles]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertStatus]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertStatus]

IF OBJECT_ID(N'[dbo].[usp_UpdateStatus]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateStatus]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateStatus]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateStatus]

IF OBJECT_ID(N'[dbo].[usp_DeleteStatus]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteStatus]

IF OBJECT_ID(N'[dbo].[usp_DeleteStatusDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteStatusDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectStatus]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectStatus]

IF OBJECT_ID(N'[dbo].[usp_SelectStatusDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectStatusDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectStatusPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectStatusPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectStatusAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectStatusAll]

--endregion

GO

--region [dbo].[usp_InsertStatus]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertStatus]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertStatus]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Status] (
	[id],
	[name]
) VALUES (
	@id,
	@name
)

--endregion

GO

--region [dbo].[usp_UpdateStatus]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateStatus]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateStatus]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

UPDATE [dbo].[Status] SET
	[name] = @name
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateStatus]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateStatus]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateStatus]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Status] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Status] SET
		[name] = @name
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Status] (
		[id],
		[name]
	) VALUES (
		@id,
		@name
	)
END

--endregion

GO

--region [dbo].[usp_DeleteStatus]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteStatus]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteStatus]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Status]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteStatusDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteStatusDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteStatusDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Status]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectStatus]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectStatus]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectStatus]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Status]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectStatusDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectStatusDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectStatusDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[name]
FROM
	[dbo].[Status]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectStatusAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectStatusAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectStatusAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Status]

--endregion

GO

--region [dbo].[usp_SelectStatusPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectStatusPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectStatusPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Status]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertTransaction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertTransaction]

IF OBJECT_ID(N'[dbo].[usp_UpdateTransaction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateTransaction]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateTransaction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateTransaction]

IF OBJECT_ID(N'[dbo].[usp_DeleteTransaction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteTransaction]

IF OBJECT_ID(N'[dbo].[usp_DeleteTransactionsDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteTransactionsDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectTransaction]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTransaction]

IF OBJECT_ID(N'[dbo].[usp_SelectTransactionsDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTransactionsDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectTransactionsPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTransactionsPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectTransactionsAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTransactionsAll]

IF OBJECT_ID(N'[dbo].[usp_SelectTransactionsByorderId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTransactionsByorderId]

IF OBJECT_ID(N'[dbo].[usp_SelectTransactionsByuserId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTransactionsByuserId]

IF OBJECT_ID(N'[dbo].[usp_DeleteTransactionsByorderId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteTransactionsByorderId]

IF OBJECT_ID(N'[dbo].[usp_DeleteTransactionsByuserId]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteTransactionsByuserId]

--endregion

GO

--region [dbo].[usp_InsertTransaction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertTransaction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertTransaction]
	@id nchar(10),
	@userId nchar(10),
	@orderId nchar(10),
	@createdBy nchar(10),
	@createdAt datetime,
	@message nvarchar(255),
	@status bit
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Transactions] (
	[id],
	[userId],
	[orderId],
	[createdBy],
	[createdAt],
	[message],
	[status]
) VALUES (
	@id,
	@userId,
	@orderId,
	@createdBy,
	@createdAt,
	@message,
	@status
)

--endregion

GO

--region [dbo].[usp_UpdateTransaction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateTransaction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateTransaction]
	@id nchar(10),
	@userId nchar(10),
	@orderId nchar(10),
	@createdBy nchar(10),
	@createdAt datetime,
	@message nvarchar(255),
	@status bit
AS

SET NOCOUNT ON

UPDATE [dbo].[Transactions] SET
	[userId] = @userId,
	[orderId] = @orderId,
	[createdBy] = @createdBy,
	[createdAt] = @createdAt,
	[message] = @message,
	[status] = @status
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateTransaction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateTransaction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateTransaction]
	@id nchar(10),
	@userId nchar(10),
	@orderId nchar(10),
	@createdBy nchar(10),
	@createdAt datetime,
	@message nvarchar(255),
	@status bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Transactions] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Transactions] SET
		[userId] = @userId,
		[orderId] = @orderId,
		[createdBy] = @createdBy,
		[createdAt] = @createdAt,
		[message] = @message,
		[status] = @status
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Transactions] (
		[id],
		[userId],
		[orderId],
		[createdBy],
		[createdAt],
		[message],
		[status]
	) VALUES (
		@id,
		@userId,
		@orderId,
		@createdBy,
		@createdAt,
		@message,
		@status
	)
END

--endregion

GO

--region [dbo].[usp_DeleteTransaction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteTransaction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteTransaction]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Transactions]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteTransactionsByorderId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteTransactionsByorderId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteTransactionsByorderId]
	@orderId nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Transactions]
WHERE
	[orderId] = @orderId

GO

--endregion

GO

--region [dbo].[usp_DeleteTransactionsByuserId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteTransactionsByuserId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteTransactionsByuserId]
	@userId nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Transactions]
WHERE
	[userId] = @userId

GO

--endregion

GO

--region [dbo].[usp_DeleteTransactionsDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteTransactionsDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteTransactionsDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Transactions]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectTransaction]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTransaction]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTransaction]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[userId],
	[orderId],
	[createdBy],
	[createdAt],
	[message],
	[status]
FROM
	[dbo].[Transactions]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectTransactionsByorderId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTransactionsByorderId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTransactionsByorderId]
	@orderId nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[userId],
	[orderId],
	[createdBy],
	[createdAt],
	[message],
	[status]
FROM
	[dbo].[Transactions]
WHERE
	[orderId] = @orderId

--endregion

GO

--region [dbo].[usp_SelectTransactionsByuserId]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTransactionsByuserId]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTransactionsByuserId]
	@userId nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[userId],
	[orderId],
	[createdBy],
	[createdAt],
	[message],
	[status]
FROM
	[dbo].[Transactions]
WHERE
	[userId] = @userId

--endregion

GO

--region [dbo].[usp_SelectTransactionsDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTransactionsDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTransactionsDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[userId],
	[orderId],
	[createdBy],
	[createdAt],
	[message],
	[status]
FROM
	[dbo].[Transactions]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectTransactionsAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTransactionsAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTransactionsAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[userId],
	[orderId],
	[createdBy],
	[createdAt],
	[message],
	[status]
FROM
	[dbo].[Transactions]

--endregion

GO

--region [dbo].[usp_SelectTransactionsPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTransactionsPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTransactionsPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[userId],
	[orderId],
	[createdBy],
	[createdAt],
	[message],
	[status]
FROM
	[dbo].[Transactions]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertType]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertType]

IF OBJECT_ID(N'[dbo].[usp_UpdateType]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateType]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateType]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateType]

IF OBJECT_ID(N'[dbo].[usp_DeleteType]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteType]

IF OBJECT_ID(N'[dbo].[usp_DeleteTypesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteTypesDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectType]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectType]

IF OBJECT_ID(N'[dbo].[usp_SelectTypesDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTypesDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectTypesPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTypesPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectTypesAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectTypesAll]

--endregion

GO

--region [dbo].[usp_InsertType]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertType]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertType]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Types] (
	[id],
	[name]
) VALUES (
	@id,
	@name
)

--endregion

GO

--region [dbo].[usp_UpdateType]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateType]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateType]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

UPDATE [dbo].[Types] SET
	[name] = @name
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateType]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateType]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateType]
	@id nchar(10),
	@name nvarchar(50)
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Types] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Types] SET
		[name] = @name
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Types] (
		[id],
		[name]
	) VALUES (
		@id,
		@name
	)
END

--endregion

GO

--region [dbo].[usp_DeleteType]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteType]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteType]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Types]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteTypesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteTypesDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteTypesDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Types]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectType]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectType]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectType]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Types]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectTypesDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTypesDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTypesDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[name]
FROM
	[dbo].[Types]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectTypesAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTypesAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTypesAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Types]

--endregion

GO

--region [dbo].[usp_SelectTypesPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectTypesPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectTypesPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[name]
FROM
	[dbo].[Types]

--endregion

GO

--region Drop Existing Procedures

IF OBJECT_ID(N'[dbo].[usp_InsertUser]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUser]

IF OBJECT_ID(N'[dbo].[usp_UpdateUser]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_UpdateUser]

IF OBJECT_ID(N'[dbo].[usp_InsertUpdateUser]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_InsertUpdateUser]

IF OBJECT_ID(N'[dbo].[usp_DeleteUser]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteUser]

IF OBJECT_ID(N'[dbo].[usp_DeleteUsersDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_DeleteUsersDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectUser]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectUser]

IF OBJECT_ID(N'[dbo].[usp_SelectUsersDynamic]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectUsersDynamic]

IF OBJECT_ID(N'[dbo].[usp_SelectUsersPaged]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectUsersPaged]

IF OBJECT_ID(N'[dbo].[usp_SelectUsersAll]') IS NOT NULL
	DROP PROCEDURE [dbo].[usp_SelectUsersAll]

--endregion

GO

--region [dbo].[usp_InsertUser]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUser]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUser]
	@id nchar(10),
	@username nchar(25),
	@password nchar(256),
	@phoneNumber nchar(20),
	@email nchar(50),
	@DOB date,
	@fullName nvarchar(50),
	@address nvarchar(50),
	@total float,
	@status bit
AS

SET NOCOUNT ON

INSERT INTO [dbo].[Users] (
	[id],
	[username],
	[password],
	[phoneNumber],
	[email],
	[DOB],
	[fullName],
	[address],
	[total],
	[status]
) VALUES (
	@id,
	@username,
	@password,
	@phoneNumber,
	@email,
	@DOB,
	@fullName,
	@address,
	@total,
	@status
)

--endregion

GO

--region [dbo].[usp_UpdateUser]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_UpdateUser]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_UpdateUser]
	@id nchar(10),
	@username nchar(25),
	@password nchar(256),
	@phoneNumber nchar(20),
	@email nchar(50),
	@DOB date,
	@fullName nvarchar(50),
	@address nvarchar(50),
	@total float,
	@status bit
AS

SET NOCOUNT ON

UPDATE [dbo].[Users] SET
	[username] = @username,
	[password] = @password,
	[phoneNumber] = @phoneNumber,
	[email] = @email,
	[DOB] = @DOB,
	[fullName] = @fullName,
	[address] = @address,
	[total] = @total,
	[status] = @status
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_InsertUpdateUser]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_InsertUpdateUser]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_InsertUpdateUser]
	@id nchar(10),
	@username nchar(25),
	@password nchar(256),
	@phoneNumber nchar(20),
	@email nchar(50),
	@DOB date,
	@fullName nvarchar(50),
	@address nvarchar(50),
	@total float,
	@status bit
AS

SET NOCOUNT ON

IF EXISTS(SELECT [id] FROM [dbo].[Users] WHERE [id] = @id)
BEGIN
	UPDATE [dbo].[Users] SET
		[username] = @username,
		[password] = @password,
		[phoneNumber] = @phoneNumber,
		[email] = @email,
		[DOB] = @DOB,
		[fullName] = @fullName,
		[address] = @address,
		[total] = @total,
		[status] = @status
	WHERE
		[id] = @id
END
ELSE
BEGIN
	INSERT INTO [dbo].[Users] (
		[id],
		[username],
		[password],
		[phoneNumber],
		[email],
		[DOB],
		[fullName],
		[address],
		[total],
		[status]
	) VALUES (
		@id,
		@username,
		@password,
		@phoneNumber,
		@email,
		@DOB,
		@fullName,
		@address,
		@total,
		@status
	)
END

--endregion

GO

--region [dbo].[usp_DeleteUser]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteUser]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteUser]
	@id nchar(10)
AS

SET NOCOUNT ON

DELETE FROM [dbo].[Users]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_DeleteUsersDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_DeleteUsersDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_DeleteUsersDynamic]
	@WhereCondition nvarchar(500)
AS

SET NOCOUNT ON

DECLARE @SQL nvarchar(3250)

SET @SQL = '
DELETE FROM
	[dbo].[Users]
WHERE
	' + @WhereCondition

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectUser]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectUser]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectUser]
	@id nchar(10)
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[username],
	[password],
	[phoneNumber],
	[email],
	[DOB],
	[fullName],
	[address],
	[total],
	[status]
FROM
	[dbo].[Users]
WHERE
	[id] = @id

--endregion

GO

--region [dbo].[usp_SelectUsersDynamic]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectUsersDynamic]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectUsersDynamic]
	@WhereCondition nvarchar(500),
	@OrderByExpression nvarchar(250) = NULL
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

DECLARE @SQL nvarchar(3250)

SET @SQL = '
SELECT
	[id],
	[username],
	[password],
	[phoneNumber],
	[email],
	[DOB],
	[fullName],
	[address],
	[total],
	[status]
FROM
	[dbo].[Users]
WHERE
	' + @WhereCondition

IF @OrderByExpression IS NOT NULL AND LEN(@OrderByExpression) > 0
BEGIN
	SET @SQL = @SQL + '
ORDER BY
	' + @OrderByExpression
END

EXEC sp_executesql @SQL

--endregion

GO

--region [dbo].[usp_SelectUsersAll]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectUsersAll]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectUsersAll]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[username],
	[password],
	[phoneNumber],
	[email],
	[DOB],
	[fullName],
	[address],
	[total],
	[status]
FROM
	[dbo].[Users]

--endregion

GO

--region [dbo].[usp_SelectUsersPaged]

------------------------------------------------------------------------------------------------------------------------
-- Generated By:   truon using CodeSmith 6.0.0.0
-- Template:       StoredProcedures.cst
-- Procedure Name: [dbo].[usp_SelectUsersPaged]
-- Date Generated: Friday, February 19, 2021
------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE [dbo].[usp_SelectUsersPaged]
AS

SET NOCOUNT ON
SET TRANSACTION ISOLATION LEVEL READ COMMITTED

SELECT
	[id],
	[username],
	[password],
	[phoneNumber],
	[email],
	[DOB],
	[fullName],
	[address],
	[total],
	[status]
FROM
	[dbo].[Users]

--endregion

GO

